global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scheme: "https"
    static_configs:
      - targets: [$TARGET_URLS]
    basic_auth:
       username: $PROMETHEUS_USERNAME
       password: $PROMETHEUS_PASSWORD
